punishments:
  # Настройки снижения урона
  damage-reduction:
    # Количество нарушений для активации снижения урона
    threshold: 10
    # Во сколько раз снижать урон (1.5 = урон уменьшается в 1.5 раза)
    multiplier: 1.5
    # Длительность снижения урона в минутах
    duration-minutes: 5

  # Настройки кика
  kick:
    # Количество нарушений для кика
    threshold: 15
    # Причина кика
    reason: "[NAC] Пункт АЧ"

  # Настройки бана
  ban:
    # Длительность бана в днях (для повторных нарушителей)
    duration-days: 15
    # Причина бана
    reason: "[NAC] АнтиЧит"

# Настройки очистки данных
cleanup:
  # Время в часах, после которого данные игрока считаются устаревшими
  player-data-expire-hours: 24
  # Интервал очистки в минутах
  cleanup-interval-minutes: 60

# Настройки логирования
logging:
  # Логировать все нарушения в консоль
  log-violations: true
  # Логировать применение наказаний
  log-punishments: true
  # Показывать подробную информацию о проверках
  debug-checks: false